server:
  port: 8082

io:
  fileLocation: ${NND_FILE_LOCATION:}

data_exchange:
  clientId: ${NND_DE_CLIENT_ID}
  secret: ${NND_DE_SECRET}
  url: ${NND_DE_URL}
  endpoint_token: ${NND_DE_URL}${NND_DE_TOKEN:/api/auth/token}
  endpoint_de: ${NND_DE_URL}${NND_DE_DE:/api/nnd/data-exchange}
  endpoint_generic: ${NND_DE_URL}${NND_DE_GENERIC:/api/datasync}
  endpoint_generic_total_record: ${NND_DE_URL}${NND_DE_GENERIC_TOTAL_RECORD:/api/datasync/count}
nnd:
  fullLoad: ${NND_FULL_LOAD:false}
  pullLimit: ${NND_PULL_LIMIT:0}
  insertLimit: ${NND_INSERT_LIMIT:1000}

poll:
  single_time_poll_enabled: ${SINGLE_TIME_POLL:false}
  nnd:
    enabled: ${NND_POLL_ENABLED:false}
  rdb:
    enabled: ${RDB_POLL_ENABLED:false}
  rdb_modern:
    enabled: ${RDB_MODERN_POLL_ENABLED:false}
  srte:
    enabled: ${SRTE_POLL_ENABLED:false}

datasync:
  store_in_sql: ${DATASYNC_STORE_SQL:false}
  store_in_local: ${DATASYNC_STORE_LOCAL:false}
  store_in_S3: ${DATASYNC_STORE_S3:false}
  local_file_path: ${DATASYNC_LOCAL_FILE_PATH:NA}

aws:
  auth:
    static:
      key_id: ${AWS_KEY_ID:NA}
      access_key: ${AWS_ACCESS_KEY:NA}
      token: ${AWS_TOKEN:NA}
    profile:
      profile_name: ${AWS_PROFILE:NA}
  s3:
    bucket-name: ${S3_BUCKET_NAME:NA}
    region: ${S3_REGION:NA}

spring:
  application:
    name: nnd-data-poll-service
  task:
    scheduling:
      pool:
        size: 4
scheduler:
  zone: ${NBS_NND_CRON_TIME_ZONE:UTC}
  # America/New_York
  # UTC
  cron: ${NBS_NND_CRON:0 */1 * * * * }
  # "0 */5 0-2 * * *"
  # every 5 min from 12 am to 3 am
  # 0 * 0-2 * * *
  # 0 (start at zero sec), * (run every min),  0-2 (run during 12 am to 3 am), * (run every day), * (run every month), * (run every year)
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${OP_DBUSER}
    password: ${OP_DBPASSWORD}
    ingest:
      url: jdbc:sqlserver://${OP_DBSERVER};databaseName=${OP_DBNAME};encrypt=true;trustServerCertificate=true;
    rdb:
      url: jdbc:sqlserver://${OP_DBSERVER};databaseName=${RDB_DBNAME};encrypt=true;trustServerCertificate=true;
    rdb_modern:
      url: jdbc:sqlserver://${OP_DBSERVER};databaseName=${RDB_MODERN_DBNAME};encrypt=true;trustServerCertificate=true;
    srte:
      url: jdbc:sqlserver://${OP_DBSERVER};databaseName=${SRTE_DBNAME};encrypt=true;trustServerCertificate=true;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none