services:
  nnd-service:
    build:
      context: ./
      dockerfile: ./nnd-service/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - broker
    container_name: nnd-service
    environment:
      NBS_DBPASSWORD: fake.fake.fake.1234
      NBS_DBSERVER: localhost
      NBS_DBUSER: sa
      NND_AUTH_URI: http://localhost:8080/realms/NBS
    networks:
      - nnd
networks:
  nnd:
    name: nnd