SELECT 'CONDITION' AS TableName, COUNT(*) AS RecordCount FROM CONDITION
UNION ALL
SELECT 'Rdb_Date' AS TableName, COUNT(*) AS RecordCount FROM Rdb_Date
UNION ALL
SELECT 'D_PATIENT' AS TableName, COUNT(*) AS RecordCount FROM D_PATIENT
UNION ALL
SELECT 'INVESTIGATION' AS TableName, COUNT(*) AS RecordCount FROM INVESTIGATION
UNION ALL
SELECT 'CASE_COUNT' AS TableName, COUNT(*) AS RecordCount FROM CASE_COUNT
UNION ALL
SELECT 'BMIRD_CASE' AS TableName, COUNT(*) AS RecordCount FROM BMIRD_CASE
UNION ALL
SELECT 'RUBELLA_CASE' AS TableName, COUNT(*) AS RecordCount FROM RUBELLA_CASE
UNION ALL
SELECT 'PERTUSSIS_CASE' AS TableName, COUNT(*) AS RecordCount FROM PERTUSSIS_CASE
UNION ALL
SELECT 'HEPATITIS_CASE' AS TableName, COUNT(*) AS RecordCount FROM HEPATITIS_CASE
UNION ALL
SELECT 'GENERIC_CASE' AS TableName, COUNT(*) AS RecordCount FROM GENERIC_CASE
UNION ALL
SELECT 'MEASLES_CASE' AS TableName, COUNT(*) AS RecordCount FROM MEASLES_CASE
UNION ALL
SELECT 'HEPATITIS_DATAMART' AS TableName, COUNT(*) AS RecordCount FROM HEPATITIS_DATAMART
UNION ALL
SELECT 'CONFIRMATION_METHOD' AS TableName, COUNT(*) AS RecordCount FROM CONFIRMATION_METHOD
UNION ALL
SELECT 'CONFIRMATION_METHOD_GROUP' AS TableName, COUNT(*) AS RecordCount FROM CONFIRMATION_METHOD_GROUP
UNION ALL
SELECT 'D_INTERVIEW' AS TableName, COUNT(*) AS RecordCount FROM D_INTERVIEW
UNION ALL
SELECT 'D_CASE_MANAGEMENT' AS TableName, COUNT(*) AS RecordCount FROM D_CASE_MANAGEMENT
UNION ALL
SELECT 'VAR_PAM_LDF' AS TableName, COUNT(*) AS RecordCount FROM VAR_PAM_LDF
UNION ALL
SELECT 'F_VAR_PAM' AS TableName, COUNT(*) AS RecordCount FROM F_VAR_PAM
UNION ALL
SELECT 'LDF_DATA' AS TableName, COUNT(*) AS RecordCount FROM LDF_DATA
UNION ALL
SELECT 'LDF_FOODBORNE' AS TableName, COUNT(*) AS RecordCount FROM LDF_FOODBORNE
UNION ALL
SELECT 'NOTIFICATION_EVENT' AS TableName, COUNT(*) AS RecordCount FROM NOTIFICATION_EVENT
UNION ALL
SELECT 'D_INV_ADMINISTRATIVE' AS TableName, COUNT(*) AS RecordCount FROM D_INV_ADMINISTRATIVE
UNION ALL
SELECT 'D_INV_EPIDEMIOLOGY' AS TableName, COUNT(*) AS RecordCount FROM D_INV_EPIDEMIOLOGY
UNION ALL
SELECT 'D_INV_HIV' AS TableName, COUNT(*) AS RecordCount FROM D_INV_HIV
UNION ALL
SELECT 'D_INV_LAB_FINDING' AS TableName, COUNT(*) AS RecordCount FROM D_INV_LAB_FINDING
UNION ALL
SELECT 'D_INV_MEDICAL_HISTORY' AS TableName, COUNT(*) AS RecordCount FROM D_INV_MEDICAL_HISTORY
UNION ALL
SELECT 'D_INV_RISK_FACTOR' AS TableName, COUNT(*) AS RecordCount FROM D_INV_RISK_FACTOR
UNION ALL
SELECT 'D_INV_TREATMENT' AS TableName, COUNT(*) AS RecordCount FROM D_INV_TREATMENT
UNION ALL
SELECT 'D_INV_VACCINATION' AS TableName, COUNT(*) AS RecordCount FROM D_INV_VACCINATION
UNION ALL
SELECT 'F_INTERVIEW_CASE' AS TableName, COUNT(*) AS RecordCount FROM F_INTERVIEW_CASE
UNION ALL
SELECT 'F_PAGE_CASE' AS TableName, COUNT(*) AS RecordCount FROM F_PAGE_CASE
UNION ALL
SELECT 'F_STD_PAGE_CASE' AS TableName, COUNT(*) AS RecordCount FROM F_STD_PAGE_CASE
UNION ALL
SELECT 'TREATMENT' AS TableName, COUNT(*) AS RecordCount FROM TREATMENT
UNION ALL
SELECT 'TREATMENT_EVENT' AS TableName, COUNT(*) AS RecordCount FROM TREATMENT_EVENT
ORDER BY RecordCount DESC;