-- BMIRD_CASE
SELECT COUNT(*)
FROM BMIRD_CASE
         JOIN INVESTIGATION ON BMIRD_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- BMIRD_MULTI_VALUE_FIELD_GROUP
SELECT COUNT(*)
FROM BMIRD_MULTI_VALUE_FIELD_GROUP
         JOIN BMIRD_CASE ON BMIRD_MULTI_VALUE_FIELD_GROUP.BMIRD_MULTI_VAL_GRP_KEY = BMIRD_CASE.BMIRD_MULTI_VAL_GRP_KEY
         JOIN INVESTIGATION ON BMIRD_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- CASE_COUNT
SELECT COUNT(*)
FROM CASE_COUNT AS A
         INNER JOIN INVESTIGATION AS B ON A.INVESTIGATION_KEY = B.INVESTIGATION_KEY
WHERE B.ADD_TIME :operator :timestamp OR B.LAST_CHG_TIME :operator :timestamp;

-- CODE_TO_CODE (SRTE)
SELECT COUNT(*)
FROM CODE_TO_CODE
WHERE LAST_CHG_TIME :operator :timestamp;

-- CONDITION
SELECT COUNT(*)
FROM CONDITION
         JOIN INVESTIGATION ON CONDITION.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- CONDITION_CODE (SRTE)
SELECT COUNT(*)
FROM CONDITION_CODE
WHERE LAST_CHG_TIME :operator :timestamp;

-- CONFIRMATION_METHOD
SELECT COUNT(*)
FROM CONFIRMATION_METHOD
         JOIN INVESTIGATION ON CONFIRMATION_METHOD.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- CONFIRMATION_METHOD_GROUP
SELECT COUNT(*)
FROM CONFIRMATION_METHOD_GROUP
         JOIN INVESTIGATION ON CONFIRMATION_METHOD_GROUP.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_CASE_MANAGEMENT
SELECT COUNT(*)
FROM D_CASE_MANAGEMENT
         JOIN INVESTIGATION ON D_CASE_MANAGEMENT.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_INTERVIEW
SELECT COUNT(*)
FROM D_INTERVIEW
WHERE D_INTERVIEW.ADD_TIME :operator :timestamp OR D_INTERVIEW.LAST_CHG_TIME :operator :timestamp;

-- D_INV_ADMINISTRATIVE
SELECT COUNT(*)
FROM D_INV_ADMINISTRATIVE
         JOIN F_PAGE_CASE ON D_INV_ADMINISTRATIVE.D_INV_ADMINISTRATIVE_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_INV_EPIDEMIOLOGY
SELECT COUNT(*)
FROM D_INV_EPIDEMIOLOGY
         JOIN F_PAGE_CASE ON D_INV_EPIDEMIOLOGY.D_INV_EPIDEMIOLOGY_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_INV_HIV
SELECT COUNT(*)
FROM D_INV_HIV
         JOIN F_PAGE_CASE ON D_INV_HIV.D_INV_HIV_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_INV_LAB_FINDING
SELECT COUNT(*)
FROM D_INV_LAB_FINDING
         JOIN F_PAGE_CASE ON D_INV_LAB_FINDING.D_INV_LAB_FINDING_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_INV_MEDICAL_HISTORY
SELECT COUNT(*)
FROM D_INV_MEDICAL_HISTORY
         JOIN F_PAGE_CASE ON D_INV_MEDICAL_HISTORY.D_INV_MEDICAL_HISTORY_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_INV_RISK_FACTOR
SELECT COUNT(*)
FROM D_INV_RISK_FACTOR
         JOIN F_PAGE_CASE ON D_INV_RISK_FACTOR.D_INV_RISK_FACTOR_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_INV_TREATMENT
SELECT COUNT(*)
FROM D_INV_TREATMENT
         JOIN F_PAGE_CASE ON D_INV_TREATMENT.D_INV_TREATMENT_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_INV_VACCINATION
SELECT COUNT(*)
FROM D_INV_VACCINATION
         JOIN F_PAGE_CASE ON D_INV_VACCINATION.D_INV_VACCINATION_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_ORGANIZATION
SELECT COUNT(*)
FROM D_ORGANIZATION
WHERE LAST_CHG_TIME :operator :timestamp;

-- D_PATIENT
SELECT COUNT(*)
FROM D_PATIENT
WHERE LAST_CHG_TIME :operator :timestamp;

-- D_PCR_SOURCE_GROUP
SELECT COUNT(*)
FROM D_PCR_SOURCE_GROUP
         JOIN F_VAR_PAM ON F_VAR_PAM.D_PCR_SOURCE_GROUP_KEY = D_PCR_SOURCE_GROUP.D_PCR_SOURCE_GROUP_KEY
         JOIN INVESTIGATION ON F_VAR_PAM.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.ADD_TIME :operator :timestamp OR INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_PROVIDER
SELECT COUNT(*)
FROM D_PROVIDER
WHERE PROVIDER_LAST_CHANGE_TIME :operator :timestamp;

-- D_RASH_LOC_GEN_GROUP
SELECT COUNT(*)
FROM D_RASH_LOC_GEN_GROUP
         JOIN F_VAR_PAM ON F_VAR_PAM.D_RASH_LOC_GEN_GROUP_KEY = D_RASH_LOC_GEN_GROUP.D_RASH_LOC_GEN_GROUP_KEY
         JOIN INVESTIGATION ON F_VAR_PAM.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.ADD_TIME :operator :timestamp OR INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- D_VAR_PAM
SELECT COUNT(*)
FROM D_VAR_PAM
         JOIN F_VAR_PAM ON F_VAR_PAM.D_VAR_PAM_KEY = D_VAR_PAM.D_VAR_PAM_KEY
         JOIN INVESTIGATION ON F_VAR_PAM.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.ADD_TIME :operator :timestamp OR INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- F_INTERVIEW_CASE
SELECT COUNT(*)
FROM F_INTERVIEW_CASE
         JOIN INVESTIGATION ON F_INTERVIEW_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
         JOIN D_INTERVIEW ON F_INTERVIEW_CASE.D_INTERVIEW_KEY = D_INTERVIEW.D_INTERVIEW_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp OR D_INTERVIEW.ADD_TIME :operator :timestamp OR D_INTERVIEW.LAST_CHG_TIME :operator :timestamp;

-- F_PAGE_CASE
SELECT COUNT(*)
FROM F_PAGE_CASE
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- F_STD_PAGE_CASE
SELECT COUNT(*)
FROM F_STD_PAGE_CASE
         JOIN INVESTIGATION ON F_STD_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- F_VAR_PAM
SELECT COUNT(*)
FROM F_VAR_PAM
         JOIN INVESTIGATION ON F_VAR_PAM.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.ADD_TIME :operator :timestamp OR INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- GENERIC_CASE
SELECT COUNT(*)
FROM GENERIC_CASE
         JOIN INVESTIGATION ON GENERIC_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- HEPATITIS_CASE
SELECT COUNT(*)
FROM HEPATITIS_CASE
         JOIN INVESTIGATION ON HEPATITIS_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- HEPATITIS_DATAMART
SELECT COUNT(*)
FROM HEPATITIS_DATAMART
         JOIN INVESTIGATION ON HEPATITIS_DATAMART.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- INVESTIGATION
SELECT COUNT(*)
FROM INVESTIGATION
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- LDF_DATA
SELECT COUNT(*)
FROM LDF_DATA
         JOIN LDF_GROUP ON LDF_DATA.LDF_GROUP_KEY = LDF_GROUP.LDF_GROUP_KEY
         JOIN INVESTIGATION ON LDF_GROUP.BUSINESS_OBJECT_UID = INVESTIGATION.CASE_UID
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- LDF_FOODBORNE
SELECT COUNT(*)
FROM LDF_FOODBORNE
         JOIN INVESTIGATION ON LDF_FOODBORNE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- MEASLES_CASE
SELECT COUNT(*)
FROM MEASLES_CASE
         JOIN INVESTIGATION ON MEASLES_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- NOTIFICATION
SELECT COUNT(*)
FROM NOTIFICATION N
WHERE N.NOTIFICATION_LAST_CHANGE_TIME :operator :timestamp
   OR (N.NOTIFICATION_LAST_CHANGE_TIME IS NULL AND EXISTS (
    SELECT 1
    FROM NOTIFICATION_EVENT NE
             JOIN INVESTIGATION I ON NE.INVESTIGATION_KEY = I.INVESTIGATION_KEY
    WHERE NE.NOTIFICATION_KEY = N.NOTIFICATION_KEY AND I.LAST_CHG_TIME :operator :timestamp));

-- NOTIFICATION_EVENT
SELECT COUNT(*)
FROM NOTIFICATION_EVENT
         JOIN INVESTIGATION ON NOTIFICATION_EVENT.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- PERTUSSIS_CASE
SELECT COUNT(*)
FROM PERTUSSIS_CASE
         JOIN INVESTIGATION ON PERTUSSIS_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- Rdb_Date
SELECT COUNT(*)
FROM Rdb_Date
WHERE LAST_CHG_TIME :operator :timestamp;

-- RUBELLA_CASE
SELECT COUNT(*)
FROM RUBELLA_CASE
         JOIN INVESTIGATION ON RUBELLA_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- TREATMENT
SELECT COUNT(*)
FROM TREATMENT
         JOIN TREATMENT_EVENT ON TREATMENT.TREATMENT_KEY = TREATMENT_EVENT.TREATMENT_KEY
         JOIN INVESTIGATION ON TREATMENT_EVENT.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- TREATMENT_EVENT
SELECT COUNT(*)
FROM TREATMENT_EVENT
         JOIN INVESTIGATION ON TREATMENT_EVENT.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME :operator :timestamp;

-- VAR_PAM_LDF
SELECT COUNT(*)
FROM VAR_PAM_LDF
         JOIN INVESTIGATION ON VAR_PAM_LDF.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE VAR_PAM_LDF.ADD_TIME :operator :timestamp OR INVESTIGATION.LAST_CHG_TIME :operator :timestamp;
