server:
  port: 8081

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: nnd-data-exchange-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${NND_AUTH_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

auth:
  token-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
  introspect-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token/introspect

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${NBS_DBUSER}
    password: ${NBS_DBPASSWORD}
    msg:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_MSGOUTE;encrypt=true;trustServerCertificate=true;
    odse:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_ODSE;encrypt=true;trustServerCertificate=true;
    srte:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_SRTE;encrypt=true;trustServerCertificate=true;
    rdb:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=RDB;encrypt=true;trustServerCertificate=true;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


diserver:
  host: ${NND_SERVER_HOST:localhost:8081}