CREATE TABLE COVID_CASE_DATAMART (
                                     COVID_CASE_DATAMART_KEY bigint NOT NULL,
                                     public_health_case_uid bigint NOT NULL,
                                     INV_LOCAL_ID varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_LOCAL_ID varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ADD_TIME datetime NULL,
                                     LAST_CHG_TIME datetime NULL,
                                     CONDITION_CD varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     NOTIFICATION_SUBMIT_DT datetime NULL,
                                     NOTIFICATION_SENT_DT datetime NULL,
                                     NOTIFICATION_LOCAL_ID varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     JURISDICTION_CD varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     JURISDICTION_NM varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PROGRAM_AREA_CD varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INV_START_DT datetime NULL,
                                     INVESTIGATION_STATUS_CD varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INV_STATE_CASE_ID varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INV_LEGACY_CASE_ID varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INV_ASSIGNED_DT datetime NULL,
                                     INV_RPT_DT datetime NULL,
                                     EARLIEST_RPT_TO_CNTY_DT datetime NULL,
                                     EARLIEST_RPT_TO_ST_DT datetime NULL,
                                     RPT_SOURCE_CD varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     HSPTLIZD_IND varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     HSPTL_ADMISSION_DT datetime NULL,
                                     HSPTL_DISCHARGE_DT datetime NULL,
                                     HSPTL_DURATION_DAYS numeric(18,0) NULL,
                                     DIAGNOSIS_DT datetime NULL,
                                     ILLNESS_ONSET_DT datetime NULL,
                                     ILLNESS_END_DT datetime NULL,
                                     ILLNESS_DURATION varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ILLNESS_DURATION_UNIT varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_ONSET_AGE varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_ONSET_AGE_UNIT varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_PREGNANT_IND varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DIE_FROM_ILLNESS_IND varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INV_DEATH_DT datetime NULL,
                                     DAYCARE_ASSOC_IND varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FOOD_HANDLER_IND varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OUTBREAK_IND varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OUTBREAK_NAME varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DISEASE_IMPORTED_IND varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     IMPORT_FROM_CNTRY varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     IMPORT_FROM_STATE varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     IMPORT_FROM_CITY varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     IMPORT_FROM_CNTY varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRANSMISSION_MODE_CD varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DETECT_METHOD_CD varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INV_CASE_STATUS varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CASE_RPT_MMWR_WK varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CASE_RPT_MMWR_YR varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INV_COMMENTS varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CTT_INV_PRIORITY_CD varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CTT_INFECTIOUS_FROM_DT datetime NULL,
                                     CTT_INFECTIOUS_TO_DT datetime NULL,
                                     CTT_INV_STATUS varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CTT_INV_COMMENTS varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CONFIRMATION_METHOD varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CONFIRMATION_DT datetime NULL,
                                     NOTES varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_GEN_COMMENTS varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_FIRST_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_MIDDLE_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_LAST_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_NAME_SUFFIX varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_DOB datetime NULL,
                                     PATIENT_AGE_REPORTED varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_AGE_RPTD_UNIT varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_BIRTH_COUNTRY varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_CURRENT_SEX char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_DECEASED_IND varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_DECEASED_DT datetime NULL,
                                     PATIENT_MARITAL_STS varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_STREET_ADDR_1 varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_STREET_ADDR_2 varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_CITY varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_STATE varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_ZIP varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_COUNTY varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_COUNTRY varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_TEL_HOME varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_PHONE_WORK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_PHONE_EXT_WORK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_TEL_CELL varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_EMAIL varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_ETHNICITY varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PATIENT_RACE_CALC varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     HOSPITAL_NAME varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PHC_INV_LAST_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PHC_INV_FIRST_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PHYS_LAST_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PHYS_FIRST_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PHYS_TEL_WORK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PHYS_TEL_EXT_WORK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RPT_PRV_LAST_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RPT_PRV_FIRST_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RPT_PRV_TEL_WORK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RPT_PRV_TEL_EXT_WORK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RPT_ORG_NAME varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RPT_ORG_TEL_WORK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RPT_ORG_TEL_EXT_WORK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ABDOMINAL_PAIN varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ABN_CHEST_XRAY_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ADENOVIRUS_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ADULT_CONG_LIVING_EXP varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     AIR_TRAVEL_EXP varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ALT_MENTAL_STATUS varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ANIMAL_EXPOSURE_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ANIMAL_TYPE_TXT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ARDS_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ATTEND_EVENTS varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     C_PNEUMONIAE_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CASE_REPORT_TO_CDC_DT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CASE_STATUS_REASON varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CDC_ASSIGNED_ID varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CHEST_PAIN_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CHILD_CARE_FACILITY varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CHILLS_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CHILLS_RIGORS varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CHINA_HC_HISTORY_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CHRONIC_LIVER_DIS_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CHRONIC_LUNG_DIS_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CHRONIC_RENAL_DIS_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CNTRY_USUAL_RESID varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ContactOther varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ContactOthSpecify varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CORONAVIRUS_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CORRECTIONAL_EXP varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CORYZA_RUNNY_NOSE_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     COUGH_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CRUISE_TRAVEL_EXP varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CTT_CONF_CASE_COMM varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CTT_CONF_CASE_HLTHCR varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CTT_CONF_CASE_HSHLD varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CTT_CONF_CASE_PAT_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CURRENT_SMOKER_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CV_DISEASE_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CYANOSIS_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DGMQ_ID varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DIABETES_MELLITUS_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DIARRHEA varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DIFFICULT_BREATH_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DOSES_PRIOR_ONSET_NBR varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DueDate varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DYSPNEA_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     EDUCATIONAL_EXP varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     EKG_ABNORMAL varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     EPI_LINKED_CASE_ID2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     EPI_LINKED_CASE_ID3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FATIGUE_MALAISE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FEVER varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FEVER_HIGHEST_TMP_NBR varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FEVERISH_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FIRST_RPT_TO_PHD_DT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FLU_A_PCR_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FLU_A_RAPID_AG_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FLU_B_PCR_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FLU_B_RAPID_AG_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FORMER_SMOKER_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     FRST_POS_SPEC_CLCT_DT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     H_METAPNEUMOVRS_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     HC_CONTACT_TYPE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     HCW_OCCUPATION varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     HCW_SETTING varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     HEADACHE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     HOSPITAL_ICU_STAY varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     HYPERTENSION varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ICU_ADMIT_DT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ICU_DISCHARGE_DT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     IMM_NTNL_NTFBL_CNDTN varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     IMMEDIATE_NND_DESC varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     IMMUNO_CONDITION_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INABLE_STAY_AWAKE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INABLE_TO_WAKE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INABLE_WAKE_STAY_AWAK varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INNC_NOTIFICATION_DT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     KNOWN_DEATH_DT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     LINKED_TO_CASE_ID varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     LOSS_OF_APPETITE_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     LOSS_TASTE_SMELL varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     LST_DOSE_PRIOR_ILL_DT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     M_PNEUMONIAE_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     MDH_AUTOIMMUNE_DISEASE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     MYALGIA varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     NAUSEA varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     NEURO_DISABLITY_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     NEURO_DISABLITY_INFO varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     NEURO_DISABLITY_INFO2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     NEURO_DISABLITY_INFO3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     NEW_CONFUSION varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     NEW_OLFACTORY_DISORDR varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     NEW_TASTE_DISORDER varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     NOTIF_COMMENT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OBESITY_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_CHRONIC_DIS_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_CHRONIC_DIS_TXT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_CLNCL_FINDING_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_CLNCL_FINDNG_SPEC varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_DIAGNOSIS_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_EXPOSURE_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_EXPOSURE_SPECIFY varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_PATHOGEN_TEST_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_SYMPTOM_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTHER_SYM_SPEC varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTHER_TREATMENT_SPEC varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTHER_TRTMNT_SPEC_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PARAINFLUENZA1_4_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PAT_PROCESS_STATUS varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PERSIS_PRESSURE_CHEST varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PNEUMONIA varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PREEXISTING_COND_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PREFERRED_LANGUAGE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PREGNANT_TRIMESTER varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PREGNANT_WEEKS varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PREV_INFECT_INDIVID varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PREV_ST_CASE_NUM1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PREV_ST_CASE_NUM2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PREV_ST_CASE_NUM3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PSYCH_CONDITION_SPEC varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PSYCH_CONDITION_SPEC2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PSYCH_CONDITION_SPEC3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PSYCHIATRIC_CONDITION varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PUI_REPORT_TO_CDC_DT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RECEIVED_ECMO_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RECEIVED_MV_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RESIDENT_CONGREGATE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RHINO_ENTERO_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RIGORS_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RPTNG_CNTY varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RSN_NOT_VAC_PER_ACIP varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     RSV_RSLT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SCHOOL_UNIVERSITY_EXP varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SCNDRY_DIAGNOSIS_DSC1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SCNDRY_DIAGNOSIS_DSC2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SCNDRY_DIAGNOSIS_DSC3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SEVERE_ARD_EXP_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SHIP_NAME varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SORE_THROAT_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SOURCE_CASE_ID varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SUBSTANCE_ABUSE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SYMPTOM_NOTES varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SYMPTOM_STATUS varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     Symptomatic varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TESTING_PERFORMED_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TOTAL_ECMO_DAYS varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TOTAL_MV_DAYS varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TOTAL_OTH_TRTMNT_DAYS varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRANSLATOR_REQ_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_DOMESTICALLY varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_INTERNATIONAL varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRIBAL_AFFIL_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRIBAL_ENROLLED_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRIBE_NAME varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TYPE_OF_RESIDENCE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     UNDERLYING_COND_OTH varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     UNDRLYNG_COND_SPECIFY varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     UNK_EXPOSURE_SOURCE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     US_COVID_CASE_EXP_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     US_HC_WORKER_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     VACC_PER_ACIP_REC_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     Vacc_Rcvd varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     VACCINATION_NOTES varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     VOMITING_INDICATOR varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     WHEEZING_IND varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     WKPLC_CRITICAL_INFRA varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     WKPLC_SETTING varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     WORKPLACE_EXP varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ANIMAL_TYPE varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     BINATIONAL_RPTNG_CRIT varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CASE_IDENTIFY_PROCESS varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     COVID_19_VARIANT varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ENROLLED_TRIBE_NAME varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     HIGH_RISK_TRAVEL_LOC varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INFO_SOURCE varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INTL_DSTINTION_MULTI varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ReasonForTest varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_STATE_MULTI varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRIBAL_NAME varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     WKPLC_SETTING_CODED varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ADDL_SPECIMEN_ID_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ARRIVAL_TRVL_DEST_DT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CDC_SPECIMEN_ID_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CITY_OF_EXP_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CNTRY_OF_EXP_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CNTY_OF_EXP_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CUR_OCCUPATION_TXT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CURRENT_INDUSTRY_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CURRENT_INDUSTRY_TXT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CURRENT_OCCUPATION_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DEPART_TRVL_DEST_DT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DURATION_OUTSIDE_US_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INTL_DESTINATIONS_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ISOLTE_SENT_STATE_LAB_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     LAB_RESULT_NUM_UNIT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_PATHOGEN_TST_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_PATHOGEN_TST_RSLT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PERFORMING_LAB_TYPE_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     QUANT_TEST_RESULT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPCMN_COLLECTION_DT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPCMN_SENT_TO_CDC_DT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPCMN_SENT_TO_CDC_IND_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPEC_SENT_TO_SPHL_DT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPECIMEN_ID_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPECIMEN_SOURCE_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ST_OR_PROV_OF_EXP_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     STATE_ISOLATE_ID_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TEST_RESULT_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TEST_RESULT_COMMENTS_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TEST_TYPE_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_INFORMATION_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_MODE_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_STATE_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     VHF_TRAVEL_REASON_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     WGS_ID_NBR_1 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ADDL_SPECIMEN_ID_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ARRIVAL_TRVL_DEST_DT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CDC_SPECIMEN_ID_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CITY_OF_EXP_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CNTRY_OF_EXP_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CNTY_OF_EXP_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CUR_OCCUPATION_TXT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CURRENT_INDUSTRY_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CURRENT_INDUSTRY_TXT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CURRENT_OCCUPATION_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DEPART_TRVL_DEST_DT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DURATION_OUTSIDE_US_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INTL_DESTINATIONS_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ISOLTE_SENT_STATE_LAB_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     LAB_RESULT_NUM_UNIT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_PATHOGEN_TST_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_PATHOGEN_TST_RSLT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PERFORMING_LAB_TYPE_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     QUANT_TEST_RESULT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPCMN_COLLECTION_DT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPCMN_SENT_TO_CDC_DT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPCMN_SENT_TO_CDC_IND_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPEC_SENT_TO_SPHL_DT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPECIMEN_ID_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPECIMEN_SOURCE_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ST_OR_PROV_OF_EXP_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     STATE_ISOLATE_ID_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TEST_RESULT_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TEST_RESULT_COMMENTS_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TEST_TYPE_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_INFORMATION_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_MODE_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_STATE_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     VHF_TRAVEL_REASON_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     WGS_ID_NBR_2 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ADDL_SPECIMEN_ID_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ARRIVAL_TRVL_DEST_DT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CDC_SPECIMEN_ID_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CITY_OF_EXP_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CNTRY_OF_EXP_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CNTY_OF_EXP_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CUR_OCCUPATION_TXT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CURRENT_INDUSTRY_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CURRENT_INDUSTRY_TXT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CURRENT_OCCUPATION_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DEPART_TRVL_DEST_DT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     DURATION_OUTSIDE_US_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     INTL_DESTINATIONS_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ISOLTE_SENT_STATE_LAB_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     LAB_RESULT_NUM_UNIT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_PATHOGEN_TST_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     OTH_PATHOGEN_TST_RSLT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     PERFORMING_LAB_TYPE_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     QUANT_TEST_RESULT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPCMN_COLLECTION_DT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPCMN_SENT_TO_CDC_DT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPCMN_SENT_TO_CDC_IND_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPEC_SENT_TO_SPHL_DT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPECIMEN_ID_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     SPECIMEN_SOURCE_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     ST_OR_PROV_OF_EXP_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     STATE_ISOLATE_ID_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TEST_RESULT_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TEST_RESULT_COMMENTS_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TEST_TYPE_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_INFORMATION_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_MODE_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     TRAVEL_STATE_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     VHF_TRAVEL_REASON_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     WGS_ID_NBR_3 varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                     CONSTRAINT PK__COVID_CA__B80F525F7046578C PRIMARY KEY (COVID_CASE_DATAMART_KEY)
);


CREATE TABLE COVID_LAB_CELR_DATAMART (
                                         Testing_lab_accession_number varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Testing_lab_specimen_ID varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Submitter_unique_sample_ID int NULL,
                                         Submitter_sample_ID_assigner int NULL,
                                         Testing_lab_name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Testing_lab_ID varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Testing_lab_ID_type varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Testing_lab_street_address varchar(202) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Testing_lab_city varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Testing_lab_state varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Testing_lab_zip_code varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_ID varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_ID_assigner varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
                                         Patient_ID_type varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
                                         Patient_DOB datetime NULL,
                                         Patient_gender char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_race varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_city varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_state varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_zip_code varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_county varchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_ethnicity varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_Age varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_Age_Units varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Illness_Onset_Date varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Pregnant varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Symptomatic_for_disease varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_location int NULL,
                                         Employed_in_high_risk_setting int NULL,
                                         Public_Health_Case_ID varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Specimen_type_code varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Specimen_type_description varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Specimen_type_code_system varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Specimen_type_free_text varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Specimen_collection_date_time varchar(23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Specimen_received_date_time int NULL,
                                         Ordering_entity_name varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
                                         Ordering_provider_last_name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_provider_first_name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_provider_street varchar(202) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_provider_city varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_provider_state varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_provider_zip_code varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_facility_name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_facility_street varchar(202) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_facility_city varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_facility_state varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_facility_zip_code varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_facility_phone_number varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Order_result_status varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Date_result_released datetime NULL,
                                         Ordered_test_code varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordered_test_description varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordered_test_code_system varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_performed_code varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_performed_description varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_performed_code_system varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_result_coded varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_result_description varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_result_code_system varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_Result_free_text varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_result_comparator varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_result_number numeric(15,5) NULL,
                                         Test_result_number_separator varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_result_number2 numeric(15,5) NULL,
                                         Test_result_units varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Reference_range varchar(41) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Abnormal_flag varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_method_description int NULL,
                                         Test_result_status varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Test_date datetime NULL,
                                         Reporting_facility_name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Reporting_facility_ID varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Report_facil_data_source_app int NULL,
                                         csv_file_version_no varchar(11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
                                         File_created_date datetime NOT NULL,
                                         Employed_in_healthcare varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         First_test varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Hospitalized varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         ICU varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Resident_congregate_setting varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Most_recent_test_date int NULL,
                                         Most_recent_test_result int NULL,
                                         Most_recent_test_type int NULL,
                                         Disease_symptoms int NULL,
                                         Patient_occupation int NULL,
                                         Patient_residency_type int NULL,
                                         Ordering_facility_county varchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_provider_county varchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Ordering_provider_ID varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Patient_death_date datetime NULL,
                                         Patient_death_indicator varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Specimen_source_site_code varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Specimen_source_site_code_sys int NULL,
                                         Specimen_source_site_descrip varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Order_test_date datetime NULL,
                                         Testing_lab_county varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Device_instance_ID_1 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Device_instance_ID_2 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Device_type_ID_1 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                         Device_type_ID_2 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);


CREATE TABLE COVID_LAB_DATAMART (
                                    COVID_LAB_DATAMART_KEY bigint NOT NULL,
                                    Lab_Local_ID varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Ordered_Test_Cd varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Ordered_Test_Desc varchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Ordered_Test_Code_System varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Order_test_date datetime NULL,
                                    Electronic_Ind char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Program_Area_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Jurisdiction_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Lab_Report_Dt datetime NULL,
                                    Lab_Rpt_Received_By_PH_Dt datetime NULL,
                                    Order_result_status varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Jurisdiction_Nm varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Specimen_Cd varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Specimen_Desc varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Specimen_type_free_text varchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Specimen_Id varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Specimen_Source_Site_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Specimen_Source_Site_Desc varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Testing_Lab_Accession_Number varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Lab_Added_Dt datetime NULL,
                                    Lab_Update_Dt datetime NULL,
                                    Specimen_Coll_Dt datetime NULL,
                                    Resulted_Test_Cd varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Resulted_Test_Desc varchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Resulted_Test_Code_System varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Device_Instance_Id_1 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Device_Instance_Id_2 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Test_result_status varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Test_Method_Desc varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Device_Type_Id_1 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Device_Type_Id_2 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Perform_Facility_Name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Testing_lab_Address_One varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Testing_lab_Address_Two varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Testing_lab_Country varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Testing_lab_County varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Testing_lab_County_Desc varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Testing_lab_City varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Testing_lab_State_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Testing_lab_State varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Testing_lab_Zip_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Result_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Result_Cd_Sys varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Result_Desc varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Text_Result_Desc nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Numeric_Comparator_Cd varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Numeric_Value_1 numeric(15,5) NULL,
                                    Numeric_Value_2 numeric(15,5) NULL,
                                    Numeric_Unit_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Numeric_Low_Range varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Numeric_High_Range varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Numeric_Separator_Cd varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Interpretation_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Interpretation_Desc varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                    Result_Comments nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Result] nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Result_Category varchar(13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Last_Name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Middle_Name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    First_Name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Patient_Local_ID varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Current_Sex_Cd char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Age_Reported varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Age_Unit_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Birth_Dt datetime NULL,
    Patient_Death_Date datetime NULL,
    Patient_Death_Ind varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Phone_Number varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Address_One varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Address_Two varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    City varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    State_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    State varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Zip_Code varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    County_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    County_Desc varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Patient_Race_Calc nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Patient_Ethnicity varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_Name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_Address_One varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_Address_Two varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_Country varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_County varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_County_Desc varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_City varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_State_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_State varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_Zip_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_Clia varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_Phone_Nbr varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Reporting_Facility_Phone_Ext varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_Name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_Address_One varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_Address_Two varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_Country varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_County varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_County_Desc varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_City varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_State_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_State varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_Zip_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_Phone_Nbr varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Facility_Phone_Ext varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_First_Name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_Last_Name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_Address_One varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_Address_Two varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_Country varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_County varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_County_Desc varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_City varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_State_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_State varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_Zip_Cd varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_Phone_Nbr varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_Phone_Ext varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Ordering_Provider_Id varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Associated_Case_ID nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    Observation_Uid bigint NOT NULL,
    EMPLOYED_IN_HEALTHCARE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FIRST_TEST varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    HOSPITALIZED varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    ICU varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    ILLNESS_ONSET_DATE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    PATIENT_AGE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    PREGNANT varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    RESIDENT_CONGREGATE_SETTING varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    SYMPTOMATIC_FOR_DISEASE varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT PK__COVID_LA__31578C69126DCC01 PRIMARY KEY (COVID_LAB_DATAMART_KEY)
    );
