CREATE DATABASE NBS_MSGOUTE;

CREATE LOGIN nbs_ods WITH PASSWORD = 'ods'
GO

use NBS_MSGOUTE
GO
CREATE USER nbs_ods FOR LOGIN nbs_ods
GO
ALTER USER nbs_ods WITH DEFAULT_SCHEMA=dbo
GO
ALTER ROLE db_owner ADD MEMBER nbs_ods
GO