SELECT 'ACT' AS TableName, COUNT(*) AS RecordCount FROM ACT
UNION ALL
SELECT 'ACT_RELATIONSHIP', COUNT(*) FROM ACT_RELATIONSHIP
UNION ALL
SELECT 'ENTITY', COUNT(*) FROM ENTITY
UNION ALL
SELECT 'OBSERVATION', COUNT(*) FROM OBSERVATION
UNION ALL
SELECT 'PARTICIPATION', COUNT(*) FROM PARTICIPATION
UNION ALL
SELECT 'PERSON', COUNT(*) FROM PERSON
UNION ALL
SELECT 'ROLE', COUNT(*) FROM ROLE;
