-- Declare the variable
DECLARE @timestamp DATETIME;

-- Set the variable value
SET @timestamp = '2024-01-01 12:00:00';

SELECT 'BMIRD_CASE' AS table_name, COUNT(*) AS count_value
FROM BMIRD_CASE
         JOIN INVESTIGATION ON BMIRD_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'BMIRD_MULTI_VALUE_FIELD_GROUP' AS table_name, COUNT(*) AS count_value
FROM BMIRD_MULTI_VALUE_FIELD_GROUP
         JOIN BMIRD_CASE ON BMIRD_MULTI_VALUE_FIELD_GROUP.BMIRD_MULTI_VAL_GRP_KEY = BMIRD_CASE.BMIRD_MULTI_VAL_GRP_KEY
         JOIN INVESTIGATION ON BMIRD_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'CASE_COUNT' AS table_name, COUNT(*) AS count_value
FROM CASE_COUNT AS A
         INNER JOIN INVESTIGATION AS B ON A.INVESTIGATION_KEY = B.INVESTIGATION_KEY
WHERE B.ADD_TIME <= :timestamp OR B.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'CONDITION' AS table_name, COUNT(*) AS count_value
FROM CONDITION

UNION ALL

SELECT 'CONFIRMATION_METHOD' AS table_name, COUNT(*) AS count_value
FROM CONFIRMATION_METHOD

UNION ALL

SELECT 'CONFIRMATION_METHOD_GROUP' AS table_name, COUNT(*) AS count_value
FROM CONFIRMATION_METHOD_GROUP
         JOIN INVESTIGATION ON CONFIRMATION_METHOD_GROUP.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_CASE_MANAGEMENT' AS table_name, COUNT(*) AS count_value
FROM D_CASE_MANAGEMENT
         JOIN INVESTIGATION ON D_CASE_MANAGEMENT.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_INTERVIEW' AS table_name, COUNT(*) AS count_value
FROM D_INTERVIEW
WHERE D_INTERVIEW.ADD_TIME <= :timestamp OR D_INTERVIEW.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_INV_ADMINISTRATIVE' AS table_name, COUNT(*) AS count_value
FROM D_INV_ADMINISTRATIVE
         JOIN F_PAGE_CASE ON D_INV_ADMINISTRATIVE.D_INV_ADMINISTRATIVE_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_INV_EPIDEMIOLOGY' AS table_name, COUNT(*) AS count_value
FROM D_INV_EPIDEMIOLOGY
         JOIN F_PAGE_CASE ON D_INV_EPIDEMIOLOGY.D_INV_EPIDEMIOLOGY_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_INV_HIV' AS table_name, COUNT(*) AS count_value
FROM D_INV_HIV
         JOIN F_PAGE_CASE ON D_INV_HIV.D_INV_HIV_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_INV_LAB_FINDING' AS table_name, COUNT(*) AS count_value
FROM D_INV_LAB_FINDING
         JOIN F_PAGE_CASE ON D_INV_LAB_FINDING.D_INV_LAB_FINDING_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_INV_MEDICAL_HISTORY' AS table_name, COUNT(*) AS count_value
FROM D_INV_MEDICAL_HISTORY
         JOIN F_PAGE_CASE ON D_INV_MEDICAL_HISTORY.D_INV_MEDICAL_HISTORY_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_INV_RISK_FACTOR' AS table_name, COUNT(*) AS count_value
FROM D_INV_RISK_FACTOR
         JOIN F_PAGE_CASE ON D_INV_RISK_FACTOR.D_INV_RISK_FACTOR_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_INV_TREATMENT' AS table_name, COUNT(*) AS count_value
FROM D_INV_TREATMENT
         JOIN F_PAGE_CASE ON D_INV_TREATMENT.D_INV_TREATMENT_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_INV_VACCINATION' AS table_name, COUNT(*) AS count_value
FROM D_INV_VACCINATION
         JOIN F_PAGE_CASE ON D_INV_VACCINATION.D_INV_VACCINATION_KEY = F_PAGE_CASE.INVESTIGATION_KEY
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_ORGANIZATION' AS table_name, COUNT(*) AS count_value
FROM D_ORGANIZATION
WHERE D_ORGANIZATION.ORGANIZATION_LAST_CHANGE_TIME <= :timestamp

UNION ALL

SELECT 'D_PATIENT' AS table_name, COUNT(*) AS count_value
FROM D_PATIENT
WHERE D_PATIENT.PATIENT_LAST_CHANGE_TIME <= :timestamp

UNION ALL

SELECT 'D_PCR_SOURCE_GROUP' AS table_name, COUNT(*) AS count_value
FROM D_PCR_SOURCE_GROUP
         JOIN F_VAR_PAM ON F_VAR_PAM.D_PCR_SOURCE_GROUP_KEY = D_PCR_SOURCE_GROUP.D_PCR_SOURCE_GROUP_KEY
         JOIN INVESTIGATION ON F_VAR_PAM.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.ADD_TIME <= :timestamp OR INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_PROVIDER' AS table_name, COUNT(*) AS count_value
FROM D_PROVIDER
WHERE D_PROVIDER.PROVIDER_LAST_CHANGE_TIME <= :timestamp

UNION ALL

SELECT 'D_RASH_LOC_GEN_GROUP' AS table_name, COUNT(*) AS count_value
FROM D_RASH_LOC_GEN_GROUP
         JOIN F_VAR_PAM ON F_VAR_PAM.D_RASH_LOC_GEN_GROUP_KEY = D_RASH_LOC_GEN_GROUP.D_RASH_LOC_GEN_GROUP_KEY
         JOIN INVESTIGATION ON F_VAR_PAM.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.ADD_TIME <= :timestamp OR INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'D_VAR_PAM' AS table_name, COUNT(*) AS count_value
FROM D_VAR_PAM
         JOIN F_VAR_PAM ON F_VAR_PAM.D_VAR_PAM_KEY = D_VAR_PAM.D_VAR_PAM_KEY
         JOIN INVESTIGATION ON F_VAR_PAM.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.ADD_TIME <= :timestamp OR INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'F_INTERVIEW_CASE' AS table_name, COUNT(*) AS count_value
FROM F_INTERVIEW_CASE
         JOIN INVESTIGATION ON F_INTERVIEW_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
         JOIN D_INTERVIEW ON F_INTERVIEW_CASE.D_INTERVIEW_KEY = D_INTERVIEW.D_INTERVIEW_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp OR D_INTERVIEW.ADD_TIME <= :timestamp OR D_INTERVIEW.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'F_PAGE_CASE' AS table_name, COUNT(*) AS count_value
FROM F_PAGE_CASE
         JOIN INVESTIGATION ON F_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'F_STD_PAGE_CASE' AS table_name, COUNT(*) AS count_value
FROM F_STD_PAGE_CASE
         JOIN INVESTIGATION ON F_STD_PAGE_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'F_VAR_PAM' AS table_name, COUNT(*) AS count_value
FROM F_VAR_PAM
         JOIN INVESTIGATION ON F_VAR_PAM.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.ADD_TIME <= :timestamp OR INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'GENERIC_CASE' AS table_name, COUNT(*) AS count_value
FROM GENERIC_CASE
         JOIN INVESTIGATION ON GENERIC_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'HEPATITIS_CASE' AS table_name, COUNT(*) AS count_value
FROM HEPATITIS_CASE
         JOIN INVESTIGATION ON HEPATITIS_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'HEPATITIS_DATAMART' AS table_name, COUNT(*) AS count_value
FROM HEPATITIS_DATAMART
WHERE REFRESH_DATETIME <= :timestamp

UNION ALL

SELECT 'INVESTIGATION' AS table_name, COUNT(*) AS count_value
FROM INVESTIGATION
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'LDF_DATA' AS table_name, COUNT(*) AS count_value
FROM LDF_DATA
         JOIN LDF_GROUP ON LDF_DATA.LDF_GROUP_KEY = LDF_GROUP.LDF_GROUP_KEY
         JOIN INVESTIGATION ON LDF_GROUP.BUSINESS_OBJECT_UID = INVESTIGATION.CASE_UID
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'LDF_FOODBORNE' AS table_name, COUNT(*) AS count_value
FROM LDF_FOODBORNE
         JOIN INVESTIGATION ON LDF_FOODBORNE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'MEASLES_CASE' AS table_name, COUNT(*) AS count_value
FROM MEASLES_CASE
         JOIN INVESTIGATION ON MEASLES_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'NOTIFICATION' AS table_name, COUNT(*) AS count_value
FROM NOTIFICATION N
WHERE N.NOTIFICATION_LAST_CHANGE_TIME <= :timestamp OR
    (N.NOTIFICATION_LAST_CHANGE_TIME IS NULL AND EXISTS
        (SELECT 1 FROM NOTIFICATION_EVENT NE
                           JOIN INVESTIGATION I ON NE.INVESTIGATION_KEY = I.INVESTIGATION_KEY
         WHERE NE.NOTIFICATION_KEY = N.NOTIFICATION_KEY AND I.LAST_CHG_TIME <= :timestamp))

UNION ALL

SELECT 'NOTIFICATION_EVENT' AS table_name, COUNT(*) AS count_value
FROM NOTIFICATION_EVENT
         JOIN INVESTIGATION ON NOTIFICATION_EVENT.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'PERTUSSIS_CASE' AS table_name, COUNT(*) AS count_value
FROM PERTUSSIS_CASE
         JOIN INVESTIGATION ON PERTUSSIS_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'Rdb_Date' AS table_name, COUNT(*) AS count_value
FROM Rdb_Date

UNION ALL

SELECT 'RUBELLA_CASE' AS table_name, COUNT(*) AS count_value
FROM RUBELLA_CASE
         JOIN INVESTIGATION ON RUBELLA_CASE.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'TREATMENT' AS table_name, COUNT(*) AS count_value
FROM TREATMENT
         JOIN TREATMENT_EVENT ON TREATMENT.TREATMENT_KEY = TREATMENT_EVENT.TREATMENT_KEY
         JOIN INVESTIGATION ON TREATMENT_EVENT.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'TREATMENT_EVENT' AS table_name, COUNT(*) AS count_value
FROM TREATMENT_EVENT
         JOIN INVESTIGATION ON TREATMENT_EVENT.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE INVESTIGATION.LAST_CHG_TIME <= :timestamp

UNION ALL

SELECT 'VAR_PAM_LDF' AS table_name, COUNT(*) AS count_value
FROM VAR_PAM_LDF
         JOIN INVESTIGATION ON VAR_PAM_LDF.INVESTIGATION_KEY = INVESTIGATION.INVESTIGATION_KEY
WHERE VAR_PAM_LDF.add_time <= :timestamp OR INVESTIGATION.LAST_CHG_TIME <= :timestamp;
