SELECT 'ANTIMICROBIAL' AS TableName, COUNT(*) AS RecordCount FROM ANTIMICROBIAL
UNION ALL
SELECT 'ANTIMICROBIAL_GROUP', COUNT(*) FROM ANTIMICROBIAL_GROUP
UNION ALL
SELECT 'BMIRD_CASE', COUNT(*) FROM BMIRD_CASE
UNION ALL
SELECT 'BMIRD_MULTI_VALUE_FIELD', COUNT(*) FROM BMIRD_MULTI_VALUE_FIELD
UNION ALL
SELECT 'BMIRD_MULTI_VALUE_FIELD_GROUP', COUNT(*) FROM BMIRD_MULTI_VALUE_FIELD_GROUP
UNION ALL
SELECT 'CASE_COUNT', COUNT(*) FROM CASE_COUNT
UNION ALL
SELECT 'CONDITION', COUNT(*) FROM CONDITION
UNION ALL
SELECT 'CONFIRMATION_METHOD', COUNT(*) FROM CONFIRMATION_METHOD
UNION ALL
SELECT 'CONFIRMATION_METHOD_GROUP', COUNT(*) FROM CONFIRMATION_METHOD_GROUP
UNION ALL
SELECT 'D_CASE_MANAGEMENT', COUNT(*) FROM D_CASE_MANAGEMENT
UNION ALL
SELECT 'D_INTERVIEW', COUNT(*) FROM D_INTERVIEW
UNION ALL
SELECT 'D_INV_ADMINISTRATIVE', COUNT(*) FROM D_INV_ADMINISTRATIVE
UNION ALL
SELECT 'D_INV_EPIDEMIOLOGY', COUNT(*) FROM D_INV_EPIDEMIOLOGY
UNION ALL
SELECT 'D_INV_HIV', COUNT(*) FROM D_INV_HIV
UNION ALL
SELECT 'D_INV_LAB_FINDING', COUNT(*) FROM D_INV_LAB_FINDING
UNION ALL
SELECT 'D_INV_MEDICAL_HISTORY', COUNT(*) FROM D_INV_MEDICAL_HISTORY
UNION ALL
SELECT 'D_INV_RISK_FACTOR', COUNT(*) FROM D_INV_RISK_FACTOR
UNION ALL
SELECT 'D_INV_TREATMENT', COUNT(*) FROM D_INV_TREATMENT
UNION ALL
SELECT 'D_INV_VACCINATION', COUNT(*) FROM D_INV_VACCINATION
UNION ALL
SELECT 'D_ORGANIZATION', COUNT(*) FROM D_ORGANIZATION
UNION ALL
SELECT 'D_PATIENT', COUNT(*) FROM D_PATIENT
UNION ALL
SELECT 'D_PCR_SOURCE', COUNT(*) FROM D_PCR_SOURCE
UNION ALL
SELECT 'D_PCR_SOURCE_GROUP', COUNT(*) FROM D_PCR_SOURCE_GROUP
UNION ALL
SELECT 'D_PROVIDER', COUNT(*) FROM D_PROVIDER
UNION ALL
SELECT 'D_RASH_LOC_GEN', COUNT(*) FROM D_RASH_LOC_GEN
UNION ALL
SELECT 'D_RASH_LOC_GEN_GROUP', COUNT(*) FROM D_RASH_LOC_GEN_GROUP
UNION ALL
SELECT 'D_VAR_PAM', COUNT(*) FROM D_VAR_PAM
UNION ALL
SELECT 'F_INTERVIEW_CASE', COUNT(*) FROM F_INTERVIEW_CASE
UNION ALL
SELECT 'F_PAGE_CASE', COUNT(*) FROM F_PAGE_CASE
UNION ALL
SELECT 'F_STD_PAGE_CASE', COUNT(*) FROM F_STD_PAGE_CASE
UNION ALL
SELECT 'F_VAR_PAM', COUNT(*) FROM F_VAR_PAM
UNION ALL
SELECT 'GENERIC_CASE', COUNT(*) FROM GENERIC_CASE
UNION ALL
SELECT 'HEP_MULTI_VALUE_FIELD', COUNT(*) FROM HEP_MULTI_VALUE_FIELD
UNION ALL
SELECT 'HEP_MULTI_VALUE_FIELD_GROUP', COUNT(*) FROM HEP_MULTI_VALUE_FIELD_GROUP
UNION ALL
SELECT 'HEPATITIS_CASE', COUNT(*) FROM HEPATITIS_CASE
UNION ALL
SELECT 'HEPATITIS_DATAMART', COUNT(*) FROM HEPATITIS_DATAMART
UNION ALL
SELECT 'INVESTIGATION', COUNT(*) FROM INVESTIGATION
UNION ALL
SELECT 'LDF_DATA', COUNT(*) FROM LDF_DATA
UNION ALL
SELECT 'LDF_FOODBORNE', COUNT(*) FROM LDF_FOODBORNE
UNION ALL
SELECT 'LDF_GROUP', COUNT(*) FROM LDF_GROUP
UNION ALL
SELECT 'MEASLES_CASE', COUNT(*) FROM MEASLES_CASE
UNION ALL
SELECT 'NOTIFICATION', COUNT(*) FROM NOTIFICATION
UNION ALL
SELECT 'NOTIFICATION_EVENT', COUNT(*) FROM NOTIFICATION_EVENT
UNION ALL
SELECT 'PERTUSSIS_CASE', COUNT(*) FROM PERTUSSIS_CASE
UNION ALL
SELECT 'PERTUSSIS_SUSPECTED_SOURCE_FLD', COUNT(*) FROM PERTUSSIS_SUSPECTED_SOURCE_FLD
UNION ALL
SELECT 'PERTUSSIS_SUSPECTED_SOURCE_GRP', COUNT(*) FROM PERTUSSIS_SUSPECTED_SOURCE_GRP
UNION ALL
SELECT 'PERTUSSIS_TREATMENT_FIELD', COUNT(*) FROM PERTUSSIS_TREATMENT_FIELD
UNION ALL
SELECT 'PERTUSSIS_TREATMENT_GROUP', COUNT(*) FROM PERTUSSIS_TREATMENT_GROUP
UNION ALL
SELECT 'RDB_DATE', COUNT(*) FROM RDB_DATE
UNION ALL
SELECT 'RUBELLA_CASE', COUNT(*) FROM RUBELLA_CASE
UNION ALL
SELECT 'STD_HIV_DATAMART', COUNT(*) FROM STD_HIV_DATAMART
UNION ALL
SELECT 'TREATMENT', COUNT(*) FROM TREATMENT
UNION ALL
SELECT 'TREATMENT_EVENT', COUNT(*) FROM TREATMENT_EVENT
UNION ALL
SELECT 'VAR_PAM_LDF', COUNT(*) FROM VAR_PAM_LDF;
