SELECT 'CODE_TO_CONDITION' AS TableName, COUNT(*) AS RecordCount FROM CODE_TO_CONDITION
UNION ALL
SELECT 'CONDITION_CODE', COUNT(*) FROM CONDITION_CODE
UNION ALL
SELECT 'JURISDICTION_CODE', COUNT(*) FROM JURISDICTION_CODE
UNION ALL
SELECT 'PROGRAM_AREA_CODE', COUNT(*) FROM PROGRAM_AREA_CODE;
