DELETE FROM ENTITY_ID;
DELETE FROM Obs_value_coded;
DELETE FROM Obs_value_numeric;
DELETE FROM Obs_value_txt;
DELETE FROM Organization_name;
DELETE FROM Organization;
DELETE FROM Public_health_case;
DELETE FROM PublicHealthCaseFact;
DELETE FROM ACT_RELATIONSHIP;
DELETE FROM PARTICIPATION;
DELETE FROM OBSERVATION;
DELETE FROM ACT;
DELETE FROM PERSON;
DELETE FROM ROLE;
DELETE FROM ENTITY;

