name: Build and push nnd-data-exchange-service image to ECR
on:
  push:
    branches:
      - main
      - master
      - update-github-action-**
    paths-ignore:
      - "docker-compose.yml"
      - "**.md"
jobs:
  sonar_scan:
    uses: ./.github/workflows/sonar.yaml
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      PASSED_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  call-build-microservice-container-workflow:
    name: Build Container
    needs: sonar_scan
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: nnd-data-exchange-service
      dockerfile_relative_path: -f ./nnd-data-exchange-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "21"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

  call-update-helm-nnd-service:
    name: Request DEV deployment
    needs: call-build-microservice-container-workflow
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Update-helm-charts.yaml@main
    with:
      microservice_name: nnd-data-exchange-service
      values_file_with_path: charts/nnd-service/values-dts1.yaml
      new_image_tag: ${{ needs.call-build-microservice-container-workflow.outputs.output_image_tag }}
    secrets:
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: create-data-sync-service-jar
      working-directory: ./nnd-data-poll-service
      run: ./gradlew build --no-daemon
    - name: upload-data-sync-service-jar
      uses: actions/upload-artifact@v4
      with:
        name: NND-data-sync-service-jar
        path: nnd-data-poll-service/build/libs/data-sync-service.jar

    - name: create-netss-message-processor-jar
      working-directory: ./netss-message-processor
      run: ./gradlew build --no-daemon
    - name: upload-netss-message-processor-jar
      uses: actions/upload-artifact@v4
      with:
        name: NETSS-message-processor-jar
        path: netss-message-processor/build/libs/netss-message-processor.jar