server:
  port: 8083

functional:
  date: ${NND_DATE}
  prior: ${NND_PRIOR}

io:
  fileLocation: ${NND_FILE_LOCATION}

spring:
  application:
    name: netss-message-processor

#scheduler:
#  zone: ${NBS_NND_CRON_TIME_ZONE:}
  # America/New_York
  # UTC
#  cron: ${NBS_NND_CRON}
  # "0 */5 0-2 * * *"
  # every 5 min from 12 am to 3 am
  # 0 * 0-2 * * *
  # 0 (start at zero sec), * (run every min),  0-2 (run during 12 am to 3 am), * (run every day), * (run every month), * (run every year)

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${OP_DBUSER}
    password: ${OP_DBPASSWORD}
    nnd:
      url: jdbc:sqlserver://${OP_DBSERVER};databaseName=${OP_DBNAME};encrypt=true;trustServerCertificate=true;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
